services:
    orynider.translateaddkey.admin.controller:
        class: orynider\translateaddkey\controller\translateaddkey
        arguments:
            - '@cache.driver'
            - '@config'
            - '@service_container'
            - '@controller.helper'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'			
            - '%core.root_path%'
            - '%core.php_ext%'
    orynider.translateaddkey.core:
        class: orynider\translateaddkey\core\translateaddkey
        arguments:
            - '@cache.driver'
            - '@config'
            - '@service_container'
            - '@controller.helper'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'			
            - '%core.root_path%'
            - '%core.php_ext%'
    orynider.translateaddkey.googletranslater:
        class: orynider\translateaddkey\google_translater\google_translater
        arguments:	   
            - '@language'	   
            - '@request'	   
    orynider.translateaddkey.listener:
        class: orynider\translateaddkey\event\listener
        arguments:
            - '@template'
            - '@config'
        tags:
            - { name: event.listener }
